### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by SantosoJoko** [joiel/booking-carwash#1]
- [x] Perancangan usecase
- [ ] Perancangan class diagram
- [ ] Perancangan Site Map
- [ ] Perancangan flowchart diagram per activity
- [ ] Perancangan database
- [ ] Perancangan UI/UX back end
- [x] Perancangan UI/UX front end
- [ ] Developing Back End
- [ ] Developing Front End
- [ ] Implementating Payment Gateway
- [ ] Testing App
- [ ] Soft Launch
- [ ] Launching

**Comment by SantosoJoko** [comment]
Ini Tasklist dari proyek kita. gua target kan deadline 2 bulan untuk menyelesaikan semua tasklist.

**Comment by SantosoJoko** [comment]
perancangan front end alias mock up sudah versi 1 silahkan di lihat di tambah, dikurangi dan di diskusikan

namanya wahbook.xls
